import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,copyFile,writeFile,rm,symlink,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';

test('installed platform bundle integrity and explicit source precedence',async t=>{
 const root=await realpath(await mkdtemp(join(tmpdir(),'qq-installed-fixture-')));t.after(()=>rm(root,{recursive:true,force:true}));
 for(const name of ['native-package.ts','native-catalog.ts','process-lock.ts','types.ts'])await copyFile(new URL('../src/'+name,import.meta.url),join(root,name));
 const pkg=join(root,'node_modules',`qq-native-client-${process.platform}-${process.arch}`);await mkdir(pkg,{recursive:true});
 await writeFile(join(pkg,'package.json'),JSON.stringify({name:`qq-native-client-${process.platform}-${process.arch}`,exports:{'./manifest.json':'./manifest.json'}}));
 const bytes=Buffer.from('native fixture; never execute'),sha=createHash('sha256').update(bytes).digest('hex');
 const version={clientVersion:'7.0.2-53644',appId:'test',qua:'test'};
 const manifest={schemaVersion:1,platform:process.platform,arch:process.arch,version,wrapper:'wrapper.node',files:[{path:'wrapper.node',url:'wrapper.node',sha256:sha}]};
 const save=async(value:unknown)=>writeFile(join(pkg,'manifest.json'),JSON.stringify(value));
 await writeFile(join(pkg,'wrapper.node'),bytes);await save(manifest);
 const {prepareNative}=await import(pathToFileURL(join(root,'native-package.ts')).href);
 const fetchBefore=globalThis.fetch;t.after(()=>{globalThis.fetch=fetchBefore;});let calls=0;
 globalThis.fetch=async()=>{calls++;throw new Error('explicit mirror selected');};
 const result=await prepareNative({dataDir:root});assert.equal(result.wrapperPath,join(pkg,'wrapper.node'));assert.deepEqual(result.version,version);assert.equal(calls,0);
 await assert.rejects(prepareNative({dataDir:root,catalogUrl:'https://example.com/catalog.json'}),/explicit mirror selected/);assert.equal(calls,1);
 await assert.rejects(prepareNative({dataDir:root,version:{...version,clientVersion:'another'}}),/explicit mirror selected/);assert.equal(calls,2);
 const local=join(root,'explicit.node');await writeFile(local,bytes);
 assert.equal((await prepareNative({dataDir:root,wrapperPath:local,version})).wrapperPath,local);assert.equal(calls,2);
 await writeFile(join(pkg,'wrapper.node'),'corrupted');await assert.rejects(prepareNative({dataDir:root}),/failed verification/);assert.equal(calls,2,'corruption does not silently download a replacement');
 await rm(join(pkg,'wrapper.node'));await symlink(local,join(pkg,'wrapper.node'));await assert.rejects(prepareNative({dataDir:root}),/failed verification/);
 await rm(join(pkg,'wrapper.node'));await writeFile(join(pkg,'wrapper.node'),bytes);
 await save({...manifest,nodeVersion:process.version,nodeConfigSha256:createHash('sha256').update(JSON.stringify(process.config)).digest('hex')});
 assert.equal((await prepareNative({dataDir:root})).wrapperPath,join(pkg,'wrapper.node'));
 await save({...manifest,nodeVersion:'v0.0.1',nodeConfigSha256:'0'.repeat(64)});await assert.rejects(prepareNative({dataDir:root}),/requires matching Node/);assert.equal(calls,2);
 await save({...manifest,nodeVersion:process.version});await assert.rejects(prepareNative({dataDir:root}),/Invalid native Node runtime constraint/);
 await save({...manifest,arch:'incorrect'});await assert.rejects(prepareNative({dataDir:root}),/does not match device/);
 await save({...manifest,files:[...manifest.files,...manifest.files]});await assert.rejects(prepareNative({dataDir:root}),/Invalid installed native manifest/);
 await save({...manifest,files:[]});await assert.rejects(prepareNative({dataDir:root}),/wrapper is missing/);
});
