import {test} from 'node:test';
import assert from 'node:assert/strict';
import {verifyUploadedMetadata,candidateMirrorCatalog} from '../scripts/upload-npm-native-mirror.mjs';
const plan={tag:'native-npm-v0.0.3-ci-123-attempt-1',sourceRelease:{commit:'a'.repeat(40),runId:'123',runAttempt:1,version:'0.0.3',releaseManifestSha256:'b'.repeat(64)}};
const assets=[{name:'linux-arm64.json',size:12,sha256:'c'.repeat(64)},{name:'mirror-plan.json',size:100,sha256:'d'.repeat(64)}];
const metadata=()=>({id:23,tag_name:plan.tag,target_commitish:plan.sourceRelease.commit,draft:false,prerelease:true,assets:assets.map((a,i)=>({...a,id:i+1,digest:'sha256:'+a.sha256,browser_download_url:`https://github.com/lc-cn/qq-native-mirror/releases/download/${plan.tag}/${a.name}`}))});
test('exact remote asset identity produces sanitized receipt',()=>{const receipt=verifyUploadedMetadata(metadata(),plan,assets);assert.equal(receipt.releaseId,23);assert.equal(receipt.remoteMetadataVerified,true);assert.equal(receipt.smallAssetReadbackVerified,false);assert.equal(receipt.catalogChanged,false);assert.equal(receipt.nativeExecuted,false);assert.deepEqual(receipt.sourceRelease,plan.sourceRelease);assert.equal(receipt.assets.length,2);assert.ok(!JSON.stringify(receipt).includes('token'));});
test('rejects missing/extra/duplicate assets, digest, size, URL and target mismatch',()=>{for(const mutate of [(m:any)=>m.target_commitish='main',(m:any)=>m.draft=true,(m:any)=>m.prerelease=false,(m:any)=>m.assets.pop(),(m:any)=>m.assets.push(m.assets[0]),(m:any)=>m.assets[0].digest='sha256:'+'0'.repeat(64),(m:any)=>m.assets[0].size++,(m:any)=>m.assets[0].browser_download_url='https://example.invalid/file',(m:any)=>m.assets[1].name=m.assets[0].name]){const m=metadata();mutate(m);assert.throws(()=>verifyUploadedMetadata(m,plan,assets));}});

test('candidate catalog targets the actual immutable uploaded manifest names',()=>{const rows=['linux-x64','linux-arm64','darwin-x64','darwin-arm64','win32-x64','win32-arm64'].map(device=>{const[platform,arch]=device.split('-');return{platform,arch,version:{clientVersion:'1.2.3',appId:'123',qua:'original'},manifestSha256:'e'.repeat(64),repoPath:'future/repo/manifest.json'};});const result=candidateMirrorCatalog({...plan,packages:rows});assert.equal(result.packages.length,6);for(const row of result.packages){assert.equal(row.manifestUrl,`https://github.com/lc-cn/qq-native-mirror/releases/download/${plan.tag}/${row.platform}-${row.arch}.json`);assert.deepEqual(row.version,rows[0].version);assert.equal(row.manifestSha256,'e'.repeat(64));assert.ok(!row.manifestUrl.includes('future'));}});
test('upload captures approved bytes privately before mutable stage changes',async()=>{const{mkdtemp,writeFile,readFile,rm,readdir}=await import('node:fs/promises');const{join}=await import('node:path');const{tmpdir}=await import('node:os');const{createHash}=await import('node:crypto');const{captureUploadAsset}=await import('../scripts/upload-npm-native-mirror.mjs');const stage=await mkdtemp(join(tmpdir(),'mirror-source-')),snapshot=await mkdtemp(join(tmpdir(),'mirror-snapshot-'));try{const approved=Buffer.from('approved immutable bytes'),sha256=createHash('sha256').update(approved).digest('hex');await writeFile(join(stage,'asset.gz'),approved);const asset=await captureUploadAsset(stage,'asset.gz','asset.gz',{sha256,size:approved.length},snapshot);await writeFile(join(stage,'asset.gz'),'changed after approval');assert.deepEqual(await readFile(asset.path),approved);assert.equal(asset.sha256,sha256);assert.equal(asset.size,approved.length);assert.ok(!asset.path.startsWith(stage));await assert.rejects(captureUploadAsset(stage,'asset.gz','wrong.gz',{sha256,size:approved.length},snapshot),/changed/);assert.deepEqual(await readdir(snapshot),['asset.gz']);}finally{await rm(stage,{recursive:true,force:true});await rm(snapshot,{recursive:true,force:true});}});
