import assert from 'node:assert/strict';
import {validateMetadata,validateLock} from './verify.mjs';
const devices=['linux-x64','linux-arm64','darwin-x64','darwin-arm64','win32-x64','win32-arm64'];
const names=[...devices.map(x=>'qq-native-client-'+x),'qq-native-client'];
const manifest={schemaVersion:1,repository:'lc-cn/qq-native-mirror',version:'0.0.1',packages:names.map(name=>({name,version:'0.0.1',integrity:'sha512-fixture'}))};
const metadata=new Map(names.map(name=>{const [os,cpu]=name.slice('qq-native-client-'.length).split('-');return[name,{name,version:'0.0.1',dist:{integrity:'sha512-fixture'},...(name==='qq-native-client'?{optionalDependencies:Object.fromEntries(names.slice(0,6).map(x=>[x,'0.0.1']))}:{os:[os],cpu:[cpu],...(os==='linux'?{libc:['glibc']}:{ }),...(os==='win32'?{engines:{node:'24.20.0'}}:{})})}];}));
validateMetadata(manifest,metadata,'0.0.1');metadata.get(names[0]).dist.integrity='bad';assert.throws(()=>validateMetadata(manifest,metadata,'0.0.1'));metadata.get(names[0]).dist.integrity='sha512-fixture';metadata.get(names[0]).cpu=['arm64'];assert.throws(()=>validateMetadata(manifest,metadata,'0.0.1'));metadata.get(names[0]).cpu=['x64'];
metadata.get(names[0]).libc=['musl'];assert.throws(()=>validateMetadata(manifest,metadata,'0.0.1'));metadata.get(names[0]).libc=['glibc'];metadata.get('qq-native-client-win32-x64').engines.node='>=24';assert.throws(()=>validateMetadata(manifest,metadata,'0.0.1'));metadata.get('qq-native-client-win32-x64').engines.node='24.20.0';validateMetadata(manifest,metadata,'0.0.1');
const lock={packages:Object.fromEntries(['qq-native-client',names[0]].map(name=>['node_modules/'+name,{version:'0.0.1',integrity:'sha512-fixture',resolved:`https://registry.npmjs.org/${name}/fixture.tgz`}] ))};validateLock(lock,manifest,'linux','x64');lock.packages['node_modules/qq-native-client'].integrity='bad';assert.throws(()=>validateLock(lock,manifest,'linux','x64'));console.log('Offline public metadata and package-lock fixtures passed; no network/native/login/publish.');
